Updating the email searching exercise
LibraryCarpentry/lc-data-intro pull request #172
Opened 2020-08-20 17:55 UTC by kylamj

Several people in my workshop yesterday pointed out that today, emails don't only have 2 or 3 letter suffixes (i.e. .org. .edu) - they now can be longer (.info, .museum). I changed the solution to the email searching exercise to reflect this.

2020-12-01 14:08 UTC, bkmgit commented
@kylamj Your solution is nice. Might it be better to use the text in #178 or some version of it?

2020-12-21 18:31 UTC, sharilaster requested changes
Per discussion on #178 I am suggesting a tweak to this PR to include both solutions. Does this look okay?

2020-12-21 18:31 UTC, sharilaster commented on _episodes/02-match-extract-strings.md
> +> > [\w.-]+\.[\w]+
Per discussion on #178 we are suggesting a small change to this pull request:

```suggestion
> >   [\w.-]+\.[\w]{2,3} OR [\w.-]+\.[\w]
```

2020-12-21 18:31 UTC, sharilaster commented on _episodes/02-match-extract-strings.md
> +> > `+` matches any word character OR digit OR character OR `-` repeated 1 or more times.
```suggestion
> > `+` matches any word character OR digit OR character OR `-` repeated 1 or more times.
> > 
> > `{2,3}` limits the number of word characters and/or digits to a two or three-character string.
```

2021-04-07 19:35 UTC, merged

2021-04-07 19:36 UTC, sharilaster commented
Thank you again for your contribution, @kylamj!